# service_samples_gpkg.R — Helpers for the validation plan persistence
# layer of <project>/data/samples.gpkg (spec 014 phase B).
#
# The systemic Base/Over plan and the action-plan observations already
# live in the same samples.gpkg via `save_samples(layer = "plots" |
# "observations")` (cf. service_project.R). This module adds a third
# layer `validation_plots` that accumulates the field validation
# placettes generated by `mod_validation_sampling`.
#
# Why a dedicated helper rather than reusing `save_samples()` :
#
#   - save_samples() overwrites the layer (`delete_layer = TRUE,
#     append = FALSE`) — that is the right semantics for a systemic
#     plan (one plan per project) but wrong for validation plans
#     which accumulate across multiple FORDEAD / FAST runs.
#   - The validation layer needs idempotency on
#     (plot_id, generated_at) so re-clicking « Persister » on the
#     same plan doesn't duplicate rows.
#   - The metadata bookkeeping is different (`validation_plots_count`
#     vs `samples_count`).


#' Persist a validation plan into samples.gpkg
#'
#' @description
#' Writes the validation plan into the `validation_plots` layer of
#' `<project_path>/data/samples.gpkg`, accumulating across runs.
#'
#' When `append = TRUE` (default), the function reads the existing
#' layer, drops rows that share `(plot_id, generated_at)` with the
#' incoming plan (idempotency), unions the two and rewrites the
#' layer. When `append = FALSE`, the layer is replaced wholesale.
#'
#' GPKG's append semantics through `sf::st_write(..., append = TRUE)`
#' are brittle as soon as schemas diverge between calls — we deliberately
#' rebuild the full layer client-side and rewrite it.
#'
#' @param plan An sf POINT with at least `plot_id` and `generated_at`
#'   columns (typically the return of [generate_validation_plan()]).
#' @param project_path Character. Filesystem root of the project
#'   (usually `app_state$current_project$path`).
#' @param layer_name Character. GPKG layer name. Default
#'   `"validation_plots"`.
#' @param append Logical. `TRUE` to merge with existing rows
#'   (idempotent on `(plot_id, generated_at)`), `FALSE` to overwrite.
#'
#' @return The total row count of the layer after the write
#'   (invisible).
#' @noRd
persist_validation_plan <- function(plan, project_path,
                                    layer_name = "validation_plots",
                                    append     = TRUE) {
  if (!inherits(plan, "sf")) {
    cli::cli_abort("plan must be an sf object")
  }
  if (!nrow(plan)) {
    cli::cli_abort("plan must contain at least one row")
  }
  if (!all(c("plot_id", "generated_at") %in% names(plan))) {
    cli::cli_abort(
      "plan must carry plot_id and generated_at columns"
    )
  }
  if (is.null(project_path) || !nzchar(project_path)) {
    cli::cli_abort("project_path is required")
  }

  data_dir <- file.path(project_path, "data")
  if (!dir.exists(data_dir)) {
    dir.create(data_dir, recursive = TRUE, showWarnings = FALSE)
  }
  gpkg <- file.path(data_dir, "samples.gpkg")

  combined <- plan
  if (isTRUE(append) && file.exists(gpkg)) {
    existing_layers <- tryCatch(sf::st_layers(gpkg)$name,
                                error = function(e) character(0))
    if (layer_name %in% existing_layers) {
      existing <- tryCatch(
        sf::st_read(gpkg, layer = layer_name, quiet = TRUE),
        error = function(e) NULL
      )
      if (!is.null(existing) && nrow(existing)) {
        key_new <- paste(plan$plot_id,
                         format(plan$generated_at, "%Y-%m-%dT%H:%M:%OS3"))
        key_old <- paste(existing$plot_id,
                         format(existing$generated_at,
                                "%Y-%m-%dT%H:%M:%OS3"))
        existing <- existing[!key_old %in% key_new, , drop = FALSE]
        if (nrow(existing)) {
          # GPKG round-trips the active geometry column name from
          # `geometry` to `geom` (GDAL default). Normalize before
          # diffing column names so the rename isn't misread as a
          # schema drift.
          existing <- .normalize_sf_geometry(existing)
          plan     <- .normalize_sf_geometry(plan)
          # rbind requires identical attribute columns. Take the
          # intersection so a real schema change between runs (cœur
          # adds / renames a column) doesn't crash the persist — the
          # diverged columns are silently dropped from the older rows.
          # Geometry is always preserved via the active sf_column.
          common <- intersect(names(existing), names(plan))
          existing <- existing[, common, drop = FALSE]
          plan     <- plan[, common, drop = FALSE]
          combined <- rbind(existing, plan)
        }
      }
    }
  }

  sf::st_write(combined, gpkg, layer = layer_name, driver = "GPKG",
               append = FALSE, delete_layer = TRUE, quiet = TRUE)
  invisible(nrow(combined))
}


# Force the active geometry column of `x` to be named "geometry".
# GPKG round-trips it to "geom" by default, which would otherwise show
# up as a phantom schema drift between the in-memory plan and a layer
# just re-read from disk.
.normalize_sf_geometry <- function(x) {
  if (!inherits(x, "sf")) return(x)
  current <- attr(x, "sf_column")
  if (identical(current, "geometry")) return(x)
  # Move the geometry to a column literally named "geometry" and drop
  # the legacy name so subsequent `names(x)` reports a single geom col.
  x[["geometry"]] <- sf::st_geometry(x)
  x[[current]] <- NULL
  sf::st_geometry(x) <- "geometry"
  x
}


#' Load the validation plan layer from samples.gpkg
#'
#' Thin reader so the module and any consumer can pull the full
#' history of validation placettes (across runs) for a project.
#'
#' @param project_path Character. Filesystem root of the project.
#' @param layer_name Character. Default `"validation_plots"`.
#' @return sf POINT or NULL when the file / layer is absent.
#' @noRd
load_validation_plan <- function(project_path,
                                 layer_name = "validation_plots") {
  if (is.null(project_path) || !nzchar(project_path)) return(NULL)
  gpkg <- file.path(project_path, "data", "samples.gpkg")
  if (!file.exists(gpkg)) return(NULL)
  available <- tryCatch(sf::st_layers(gpkg)$name,
                        error = function(e) character(0))
  if (!(layer_name %in% available)) return(NULL)
  tryCatch(
    sf::st_read(gpkg, layer = layer_name, quiet = TRUE),
    error = function(e) {
      cli::cli_warn("Failed to load validation layer: {e$message}")
      NULL
    }
  )
}
